### PR TITLE
feat: add support for linear and constant point scaling via a new property called `pointScaleMode`

### LINKED ISSUE #169: Constant point size when zooming
Is there a way to fix the size of points, so that point sizes are unaffected by the zoom? I have an extremely dense plot which requires significant zooming to read meaningful information. But it seems that I have to choose between having very large points after zooming in, or very small points when zoomed out.

### PR DESCRIPTION
**Pull request by abast**
> Write one to two sentences summarizing this PR

This introduces two new modes: 
(1) point size is kept constant, independent of zoom
(2) point size is proportional to zoom.

> What was changed in this pull request?

- the getPointScale method in index.js
- an additional attribute POINT_SCALE_MODE was introduced, which allows to switch between three modes: 'constant', 'proportional' and 'default. 

> Why is it necessary?

Fixes #169 

## Checklist

- [x] Provided a concise title as a [semantic commit message](https://www.conventionalcommits.org) (e.g. "fix: correctly handle undefined properties")
- [ ] `CHANGELOG.md` updated
- [ ] Tests added or updated
- [ ] Documentation in `README.md` added or updated
- [ ] Example(s) added or updated
- [ ] Screenshot, gif, or video attached for visual changes

### CODE REVIEW

**Review by flekschas — CHANGES_REQUESTED** [review]
Thanks for taking a stab at different point scale functions. :tada: The scaling modes look fine but we need to make a couple changes to ensure good performance.

Apart from that there are several missing aspects before I can merge the PR and cut a new release:
- The new `pointScaleMode` property needs to be documented in `README.md`
- The new `pointScaleMode` property needs to be typed in `types.d.ts`
- The new `pointScaleMode` property needs to be changeable via the `set` function and gettable via the `get` function.
- The `CHANGELOG.md` needs to be updated. Since this is a new feature, I suggest adding the change a new headline for `1.11.0`.
- The new scaling functions need to be tested. Unlike Jupyter Scatter, regl-scatterplot is rigorously tested ;)

I can help with some of this over the next days.

**Comment by flekschas** [comment]
I made a bunch of changes to address most outstanding issues. I'll commit them later today or tomorrow

**Comment by abast** [comment]
Thanks for addressing most of the outstanding issues! This is my first time working with javascript, so also thanks for the warm and encouraging response :)

**Comment by flekschas** [comment]
I can't figure out how to push to your branch so I'll merge your branch into a new one I just created and then I'll push my changes onto the new branch :)

**Review by flekschas — APPROVED** [review]

**Pull request merged**
